operate-first/operate-first-data-science-community

README.md
docs/meetup-landing-page.md

Add a link for the mailing list.

Add mailing list

---

docs/content.md
docs/meetup-landing-page.md

Updated the `content.md` file to only have the next event. And updated a number of links in `meetup-landing-page.md` to use google meet and a public calendar. 
Please test the links before merging : )

update agenda add new calendar links

---

docs/email_templates/invite_template.md
docs/email_templates/postmeetup_update.md

Add email templates

---

docs/format.md

Add format for the meetup

---

notebooks/data_obfuscation.ipynb

In this notebook, we explored an obfuscation technique `hashlib` and demonstrated it by applying it on a sample dataset. Please give your comments and feedback. 
Closes #27

Added a notebook for exploring data obfuscation technique

---

.github/ISSUE_TEMPLATE/event_template.md
.github/ISSUE_TEMPLATE/topic_submission.md

Add actionable items to the issue_template

---

docs/privacy-policy.md

Add the privacy policy for the Opf DS Community Meetup

---

notebooks/data-collection.ipynb

Added an inference notebook which would provide us a sample instruction for fetching meetup data from the opf-datacatlog bucket and description of the data. 
closes #58

Added an data-collection notebook

---

Pipfile
Pipfile.lock
notebooks/EDA_meetup_attendees.ipynb

The notebook serves the purpose of doing exploratory data analysis on operate first data science meetup attendees data (obfuscated), in order to gather some insights from it, which would then help in community building. 
Closes #57

EDA notebook for meet-up attendees obfuscated data

---

docs/content.md

This PR updates agenda for meetup 8 (#51) and meetup 9(#46). It also updates the agenda for the previous meetups' slides

Update agenda for meetup 8 and 9

---

docs/content.md

Update links for slides

---

docs/content.md

Update agenda for meetup 9 video link

---

docs/content.md

Update agenda for meetup10

---

docs/content.md

Add agenda for  [Meetup 11](https://github.com/aicoe-aiops/operate-first-data-science-community/issues/87) , and updated video and slides for #85

Update agenda for meetup 10 and 11

---

docs/format.md

Update format to include youtube naming convention

---

docs/content.md

Update agenda with video for meetup11 and agenda for meetup12

---

docs/content.md

update agenda for Meetup 12

---

docs/content.md

Agenda for meetup 13

---

docs/content.md

Resolves #103 
Adds agenda for #107

Add video and slides for meetup 15 and agenda for meetup 16

---

docs/content.md

Update agenda with video and slides link for meetup16

---

docs/content.md

Update agenda for meetup 17
